apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django-template
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: django-template
    spec:
      containers:
      - name: django-template
        image: nolram/django-template
        ports:
        - name: django-port
          containerPort: 80