apiVersion: v1
kind: Service
metadata:
  name: django-template-service
spec:
  ports:
  - port: 8002
    nodePort: 31001
    targetPort: django-port
    protocol: TCP
  selector:
    app: django-template
  type: NodePort