apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: django-template-autoscaler
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: django-template
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50