apiVersion: v1
kind: ReplicationController
metadata:
  name: django-db
spec:
  replicas: 1
  selector:
    app: django-db
  template:
    metadata:
      name: django-db
      labels:
        app: django-db
    spec:
      containers:
      - name: postgres
        image: postgres:alpine
        ports:
        - name: postgres-port
          containerPort: 5432
        env:
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: db-password

          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: db-name

          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secrets
                key: db-user
                
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: efs-pvc
      volumes:
        - name: efs-pvc
          persistentVolumeClaim:
            claimName: efs